### ISSUE TITLE
Sample SBOL 3 files use non-standard filename extensions

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOLTestSuite#18]
The sample SBOL 3 files use the following non-standard filename extensions:

| Format | File Extension |
| ------ | ------ |
| JSON-LD | `.jsonld.sbol` |
| N-Triples | `.ntriples.sbol` |
| RDF/JSON | `.rdfjson.sbol` |
| RDF/XML | `.rdfxml.sbol` |
| Turtle | `.turtle.sbol` |

These formats all have standard filename extensions. The links in the table below go to the W3C specifications
for each format. Each of these specifications documents the filename extension for the format.

| Format | File Extension |
| ------ | ------ |
| [JSON-LD](https://www.w3.org/TR/json-ld/#iana-considerations) | `.jsonld` |
| [N-Triples](https://www.w3.org/TR/n-triples/#sec-mediaReg-n-triples) | `.nt` |
| [RDF/JSON](https://www.w3.org/TR/rdf-json/#sec-mediaReg) | `.rj` |
| [RDF/XML](https://www.w3.org/TR/rdf-syntax-grammar/#section-MIME-Type) | `.rdf` |
| [Turtle](https://www.w3.org/TR/turtle/#sec-mediaReg) | `.ttl` |

If there is agreement on this proposal I'd be happy to submit a pull request with renamed files.

**Comment by goksel** [comment]
Thanks for this list. The examples now use the extensions from the second table.
