### ISSUE TITLE
SBOL3 test files use default namespace

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOLTestSuite#19]
I'm not sure how the default namespace is supposed to work in RDF/XML. What's in the `rdfxml.sbol` files now does not work properly with the online [RDF Translator](http://rdf-translator.appspot.com/). Here is a subset of `SBOL3/entity/interface/interface.rdfxml.sbol`:

```xml
<rdf:RDF
    xmlns:SO="https://identifiers.org/SO:"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:EDAM="https://identifiers.org/edam:"
    xmlns:sbol="http://sbols.org/v3#"
    xmlns:CHEBI="https://identifiers.org/CHEBI:"
    xmlns:SBO="https://identifiers.org/SBO:"
    xmlns:GO="https://identifiers.org/GO:"
    xmlns="https://sbolstandard.org/examples/">
   <sbol:Component rdf:about="aTC">
      <sbol:role rdf:resource="https://identifiers.org/CHEBI:35224"/>
      <sbol:description>aTC</sbol:description>
      <sbol:displayId>aTC</sbol:displayId>
      <sbol:name>aTC</sbol:name>
      <sbol:type rdf:resource="https://identifiers.org/SBO:0000247"/>
   </sbol:Component>
</rdf:RDF>
```

The RDF Translator translation to N-Triples lacks the `https://sbolstandard.org/examples/` prefix on the Component's URI:

```
<aTC> <http://sbols.org/v3#type> <https://identifiers.org/SBO:0000247> .
<aTC> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sbols.org/v3#Component> .
<aTC> <http://sbols.org/v3#name> "aTC" .
<aTC> <http://sbols.org/v3#displayId> "aTC" .
<aTC> <http://sbols.org/v3#role> <https://identifiers.org/CHEBI:35224> .
<aTC> <http://sbols.org/v3#description> "aTC" .
```

The same snippet of `SBOL3/entity/interface/interface.ntriples.sbol` is:

```
<https://sbolstandard.org/examples/aTC> <http://sbols.org/v3#role> <https://identifiers.org/CHEBI:35224> .
<https://sbolstandard.org/examples/aTC> <http://sbols.org/v3#description> "aTC" .
<https://sbolstandard.org/examples/aTC> <http://sbols.org/v3#displayId> "aTC" .
<https://sbolstandard.org/examples/aTC> <http://sbols.org/v3#name> "aTC" .
<https://sbolstandard.org/examples/aTC> <http://sbols.org/v3#type> <https://identifiers.org/SBO:0000247> .
<https://sbolstandard.org/examples/aTC> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sbols.org/v3#Component> .
```

Either the RDF Translator and RDFlib do not handle the default namespace properly, or the default namespace is not the right thing to use in RDF/XML files. If the files should be transitioned away from using the default namespace I can submit a pull request that uses RDF/XML files derived from the N-Triples versions as translated by the RDF Translator.

**Comment by goksel** [comment]
This issue has been fixed after including the xml:base mapping in RDF/XML serialisation. The updated file is here: https://github.com/SynBioDex/SBOLTestSuite/blob/master/SBOL3/entity/interface/interface.rdf

Please close the issue after you verify it.
