### ISSUE TITLE
SBOL3 measurement example lacks required symbol property

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOLTestSuite#23]
The spec says that om:symbol is a REQUIRED property of om:Prefix. The `https://sbolstandard.org/examples/milli` example in `SBOL3/measurement_entity/measurement/measurement.nt` (and friends) lacks an om:symbol property.

I'll also note here that the example uses property URIs that are different from the spec. That difference is noted in an issue against the spec itself: https://github.com/SynBioDex/SBOL-specification/issues/390

**Comment by tcmitchell** [comment]
Also in `SBOL3/measurement_entity/measurement/measurement.nt`, `https://sbolstandard.org/examples/litre` is lacking a REQUIRED om:symbol property.

**Comment by goksel** [comment]
Thanks Tom, I fixed this issue. I will replace the examples soon.
