### ISSUE TITLE
SBOL3 JSON-LD files are malformed

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOLTestSuite#30]
I am having trouble parsing some of the jsonld files in SBOLTestSuite/SBOL3. I am using rdflib-jsonld, which is compatible with rdflib, in Python.

For example, https://github.com/SynBioDex/SBOLTestSuite/blob/master/SBOL3/BBa_F2620_PoPSReceiver/BBa_F2620_PoPSReceiver.jsonld ends up with the wrong identities for the objects. The identities have the filename prefixed, instead of "https://synbiohub.org/public/igem/" which is the URI cited in "@vocab". Is it possible "@vocab" does not apply to object ids?

I see similar behavior in an online JSON-LD playground: https://json-ld.org/playground/
When I load the same file above in the playground they also end up with the wrong object ids. This time prefixed with the URL because I pointed the tool at the file via URL.

I get the same basic issue with SBOLTestSuite/SBOL3/entity/model/model.jsonld as well. Here is the link to this file in the JSON-LD playground since it is a simpler example: https://json-ld.org/playground/#startTab=tab-expanded&json-ld=https%3A%2F%2Fraw.githubusercontent.com%2FSynBioDex%2FSBOLTestSuite%2Fmaster%2FSBOL3%2Fentity%2Fmodel%2Fmodel.jsonld&context=%7B%7D

I suspect either the json-ld package is not up to the latest spec, or the files are malformed. It would be good to hear experiences with other json-ld packages in other languages.

**Comment by goksel** [comment]
I noticed that theRDF library I was using had an issue (https://issues.apache.org/jira/projects/JENA/issues/JENA-2069). I reported this and removed the use of short URIs in JSON-LD serialisation for SBOL entities.  I also added another RDF JSON-LD serialisation (JSON-LD expanded) in which all URIs are expanded. Hopefully, these new files should help us going forward with the JSON-LD serialisation.
