### ISSUE TITLE
Update sequence encodings in SBOL3 files

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOLTestSuite#32]
The sequence encoding URIs are changing in SBOL3 3.0.1. Update the following examples to use the new encodings:
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/BBa_F2620_PoPSReceiver
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/multicellular
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/toggle_switch

Here are the Python definitions of the new encodings:
```python
IUPAC_DNA_ENCODING = 'https://identifiers.org/edam:format_1207'
IUPAC_RNA_ENCODING = 'https://identifiers.org/edam:format_1207'
IUPAC_PROTEIN_ENCODING = 'https://identifiers.org/edam:format_1208'
INCHI_ENCODING = 'https://identifiers.org/edam:format_1197'
SMILES_ENCODING = 'https://identifiers.org/edam:format_1196'
```

**Comment by goksel** [comment]
Updated the examples with the new encodings.
